✨ 좋아요 페이지 개발, 앱바 기능구현, 곡 순서 편집 기능
wakmusic/wakmusic-pc pull request #105
Opened 2023-08-15 07:08 UTC by sandsunset

## 개요

좋아요 페이지와 여러 글로벌 컴포넌트를 작업했습니다

## 이슈

#43 

## 작업 내용

- 좋아요 페이지를 개발했습니다
- 앱바의 기능을 구현하고 검색, 왁뮤차트, 최신음악, 아티스트, 플레이리스트, 좋아요에 적용했습니다
- 앱바의 팝업, 팝다운 애니메이션을 구현했습니다
- useSelectSongs 훅에 selectCallback이 배열도 처리할 수 있도록 작업했습니다
- 드래그 앤 드롭을 통해 곡 순서를 편집할 수 있는 CustomSongs 글로벌 컴포넌트를 작업했습니다
- 탭 컴포넌트에 onClick 콜백을 추가했습니다

## 스크린샷

https://github.com/wakmusic/wakmusic-pc/assets/61652299/f49c6828-35c1-41ad-ac47-57a41046fe95

2023-08-15 11:12 UTC, minibox24 commented on src/components/globals/CustomSongs.tsx
> +    song: dummySong,
따로 더미를 두는 것 보다는 DragTarget의 song를 `Song | undefined` 로 설정하는게 더 좋을 것 같다는 생각입니다

2023-08-15 11:12 UTC, minibox24 commented on src/components/globals/CustomSongs.tsx
> +          {virtualMap(mapSongComponent)}
여긴 따로 분리하신 이유가 있는건가요? 가독성?

2023-08-15 11:12 UTC, minibox24 commented on src/components/globals/musicControllers/MusicController.tsx
> +    // 컨트롤러 에니미에션 토글
주석 오타,...!!

2023-08-15 11:14 UTC, minibox24 requested changes

2023-08-15 11:14 UTC, minibox24 commented on src/pages/user/Likes.tsx
> +        displayDefault={true}
이거 false여야할 것 같습니다

2023-08-15 11:14 UTC, minibox24 commented on src/components/globals/CustomSongs.tsx
> +interface SongsProps {
CustomSongsProps 이여야 할 것 같습니다

2023-08-15 11:15 UTC, sandsunset commented on src/components/globals/CustomSongs.tsx
> +          {virtualMap(mapSongComponent)}
애니메이션 재생중에 스크롤 높이가 바뀌는 문제 떄문에 따로 분리했습니다

2023-08-15 11:18 UTC, minibox24 requested changes
GuideBar도 편집 모드일 때 같이 위치가 바뀌면 좋을 것 같아용

2023-08-16 15:53 UTC, choshinyoung reviewed
여러 곡을 선택하고 재생을 하면 선택한 순서대로 플레이리스트에 추가되는데, 인덱스 순으로 추가되게 하는건 어떨까요

2023-08-16 22:00 UTC, unsignd requested changes

2023-08-16 22:00 UTC, unsignd commented on src/components/globals/CustomSongs.tsx
> +        }}
styled component사용해서 수정하면 좋을 것 같아요

2023-08-17 08:40 UTC, kimbuckgur approved these changes
수고 많으십니다

2023-08-17 22:59 UTC, sandsunset commented on src/components/globals/CustomSongs.tsx
> +        }}
애니메이션을 넣기 위해 자주 사용되는 스타일이라 styled component를 사용하면 성능이슈가 생길거 같습니다

2023-08-17 23:00 UTC, sandsunset commented
> 여러 곡을 선택하고 재생을 하면 선택한 순서대로 플레이리스트에 추가되는데, 인덱스 순으로 추가되게 하는건 어떨까요

@minibox24 어떤가요

2023-08-17 23:02 UTC, sandsunset commented
근데 선택한 순서대로 재생이 되야 편하지 않을까요?

2023-08-18 02:16 UTC, choshinyoung commented on src/components/globals/CustomSongs.tsx
> +        }}
`styled.div.attrs` 사용하시면 될거같습니다

2023-08-18 03:03 UTC, sandsunset commented on src/components/globals/CustomSongs.tsx
> +        }}
애니메이션 용으로 쓰려면 직접적으로 값을 태그에 넣어주는게 가장 빠르지 않을까요

2023-08-18 17:55 UTC, minibox24 requested changes
https://github.com/wakmusic/wakmusic-pc/assets/61264156/f1d9d4dd-1299-47c0-a6b0-3d5bbe3db775


뭔가 이상해요

2023-08-20 14:37 UTC, minibox24 requested changes

2023-08-20 14:37 UTC, minibox24 commented on src/templates/song.ts
> +export type OrderdSong = Song & {
typo

2023-08-20 14:38 UTC, minibox24 commented
- https://github.com/wakmusic/wakmusic-pc/pull/105/files#diff-542498e2b1738186b9242c6f9c07330c45e253268714864936111506a02ac84eR380

- https://github.com/wakmusic/wakmusic-pc/pull/105/files#diff-053d21e4202de76e5a28209af8aa72d5727f6d8cf37c2244de0887bd777e07caR40

transition에 프롭이 4개이면 맨 마지막꺼가 delay라고 하는데 0초로 설정하신 이유가 있나요?

2023-08-20 14:38 UTC, minibox24 requested changes
컨플릭트 해결도 부탁드립니다!

2023-08-20 15:07 UTC, sandsunset commented
> * https://github.com/wakmusic/wakmusic-pc/pull/105/files#diff-542498e2b1738186b9242c6f9c07330c45e253268714864936111506a02ac84eR380
> * https://github.com/wakmusic/wakmusic-pc/pull/105/files#diff-053d21e4202de76e5a28209af8aa72d5727f6d8cf37c2244de0887bd777e07caR40
> 
> transition에 프롭이 4개이면 맨 마지막꺼가 delay라고 하는데 0초로 설정하신 이유가 있나요?

작업 중에 테스트 용도로 사용하던 코드가 남아있던거 같습니다 삭제했어요

2023-08-20 15:10 UTC, minibox24 approved these changes
수고하셨습니다!

2023-08-20 15:13 UTC, merged