Feature/serviceinfo
wakmusic/wakmusic-pc pull request #114
Opened 2023-08-16 15:56 UTC by unsignd

## 개요

서비스 정보 모달을 제작하였습니다.

## 작업 내용

- 서비스 정보 모달 제작

## 스크린샷

<img width="1362" alt="Screenshot 2023-08-17 at 12 55 57 AM" src="https://github.com/wakmusic/wakmusic-pc/assets/63943594/0a08c1f4-1c70-4b5a-b3bb-7e83120eed7d">

2023-08-16 17:12 UTC, choshinyoung requested changes
모달의 아래쪽 border-radius가 디자인과 일치하지 않습니다. 따로 처리해주시면 좋을것같습니다

2023-08-16 17:12 UTC, choshinyoung commented on src/components/modals/ServiceInfoModal.tsx
> +  gap: 10px;
gap이 디자인과 일치하지 않습니다

2023-08-16 19:20 UTC, choshinyoung approved these changes

2023-08-17 01:21 UTC, minibox24 requested changes

2023-08-17 01:21 UTC, minibox24 commented on .gitignore
> +src/electron.js
이건 예전 버전에서만 쓰였던 js 파일입니다

.gitignore에 추가하지 마시고 그냥 로컬에서 파일 지워주세요

2023-08-17 01:21 UTC, minibox24 commented on src/components/modals/ServiceInfoModal.tsx
> +  ];
constants로 옮겨주세요

2023-08-17 01:21 UTC, minibox24 commented on src/assets
따로 보더가 추가된 아이콘을 추가하지 마시고 기존 AppIcon에다가 css로 보더를 추가해주세요

2023-08-17 01:23 UTC, minibox24 reviewed
솔직히 지금의 모달을 켜는 방식은 조금 모시꺵이한 것 같습니다....

가능하다면 `/info` 라우트로 간다면 이전 페이지가 배경으로 떠있고 서비스 정보 모달도 떠있는 식으로 가면 좋을 것 같아요

### 레퍼런스
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/1726fe4b-2390-4bb5-bd79-a226e6705ef4)

2023-08-17 04:11 UTC, minibox24 commented on src/main.tsx
> +              />
이거 맞아요..?

2023-08-17 06:30 UTC, minibox24 commented on src/assets
에셋 커밋이 변경되어있는데 리버트 해주세요

2023-08-17 07:43 UTC, minibox24 requested changes
'서비스 이용약관'이랑 '개인정보 처리방침' 누르면 외부 브라우저에서 창 열리는 것 까지는 구현 부탁드립니다

2023-08-17 08:44 UTC, kimbuckgur requested changes
오네가이시마수

2023-08-17 08:44 UTC, kimbuckgur commented on src/components/modals/ServiceInfoModal.tsx
> +        <Version>현재 버전 0.1.0 (5b6c01b3)</Version>
뭔가 버전은 리터럴 로 관리하는거 보다는 상수만드는거 아니면 AP가 좋을 듯 하네요 중요한 정보라고 생각되네요

2023-08-17 08:44 UTC, kimbuckgur commented on src/components/mypage/Block.tsx
> +    <Container onClick={() => (endPoint ? navigate(endPoint) : undefined)}>
<Link>를 쓰는건 어떨까요?

2023-08-18 17:45 UTC, minibox24 approved these changes

2023-08-18 17:45 UTC, merged