Fix/player
wakmusic/wakmusic-pc pull request #121
Opened 2023-08-17 20:17 UTC by choshinyoung

## 개요

플레이어 컴포넌트에서의 몇가지 픽스 작업

## 이슈

#88 

## 작업 내용

- 최대화 버튼 클릭 이외의 방법으로 최대화했을 때 아이콘 변경
- 타임라인 핸들 튀어나감 해결
- 가사가 두 줄 이상인 경우 대응
- 플레이어 플레이리스트에 virtual 적용 및 약간의 최적화

2023-08-18 17:34 UTC, minibox24 requested changes

2023-08-18 17:34 UTC, minibox24 commented on src/components/player/Timeline.tsx
> +        progress={(current / length) * 100}
`$` 붙여주세요

![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/af9cafeb-60bd-4d82-8339-b603ac98a779)

2023-08-18 18:17 UTC, minibox24 approved these changes

2023-08-19 06:30 UTC, kimbuckgur requested changes
코멘트 확인 오네가이시마스!!

2023-08-19 06:30 UTC, kimbuckgur commented on src/components/player/Default/Playlist.tsx
> +      return;
이렇게 return 하면 아마 undefind 타입이 리턴 될텐데 이것보다는 <></> 프래그먼트가  더 리턴 타입이 좋을 듯 합니다

2023-08-19 06:30 UTC, kimbuckgur commented on src/components/globals/Scroll/PlayerScroll.tsx
> +        return;
중괄호 있는게 좋을 듯 합니다

2023-08-19 06:32 UTC, minibox24 commented on src/components/player/Default/Playlist.tsx
> +      return;
요거는 useInterval의 return인 것 같아요

2023-08-19 06:41 UTC, kimbuckgur commented on src/components/player/Default/Playlist.tsx
> +      return;
아하 소데스까

2023-08-20 02:52 UTC, kimbuckgur approved these changes
수고 많으십니다

2023-08-20 03:03 UTC, merged