플레이어 재생목록 개발
wakmusic/wakmusic-pc pull request #157
Opened 2023-08-27 02:06 UTC by kimbuckgur

## 개요
플레이어 재생목록 개발

## 이슈

#63

## 작업 내용

- 플래이어 재생목록 개발

## 스크린샷
![image](https://github.com/wakmusic/wakmusic-pc/assets/80795917/e5be2c0b-afb1-4bcd-90f5-e7d40583bd15)

2023-08-27 02:21 UTC, minibox24 requested changes

2023-08-27 02:21 UTC, minibox24 commented on src/pages/playerPlaylist/PlayerPlaylist.tsx
> +    console.log(removedSongs);
디버깅 코드 지워주세요

2023-08-27 02:21 UTC, minibox24 commented on src/pages/playerPlaylist/PlayerPlaylist.tsx
> +          onDelete={isEdit ? undefined : dispatchPlayerListInfo}
순서가 바뀌어 있습니다

(편집모드가 아닐떄 삭제 버튼이 나옴)

2023-08-27 02:21 UTC, minibox24 commented on src/pages/playerPlaylist/PlayerPlaylist.tsx
> +          ]}
여기 feature들을 디자인과 동일하게 발매일, 조회수, 좋아요로 통일시켜주세요

2023-08-27 02:21 UTC, minibox24 commented on src/pages/playerPlaylist/PlayerPlaylist.tsx
순서 수정이 작동하지 않네요

2023-08-27 02:21 UTC, minibox24 commented on src/pages/playerPlaylist/PlayerPlaylist.tsx
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/650f3088-cc04-49aa-8a96-40d07b07e2bd)

활성화 시 파래져야 하네요
다시 토글시 이전 페이지로 돌아가야 할 것 같습니당

2023-08-27 03:53 UTC, kimbuckgur commented on src/pages/playerPlaylist/PlayerPlaylist.tsx
> +          onDelete={isEdit ? undefined : dispatchPlayerListInfo}
편집 모드가 아닐때면 저게 맞는거아닌가요?

2023-08-27 03:57 UTC, minibox24 commented on src/pages/playerPlaylist/PlayerPlaylist.tsx
> +          onDelete={isEdit ? undefined : dispatchPlayerListInfo}
다시 디자인 확인해봤더니 편집 모드에 관계없이 삭제 버튼이 있네요

2023-08-27 04:38 UTC, minibox24 approved these changes
수고하셨습니다! 린팅 한번만 돌려주시면 좋을 듯 하네용

2023-08-27 05:02 UTC, choshinyoung commented
플레이어 컴포넌트에서 플레이리스트 순서를 변경했을 때 플레이리스트 페이지에서도 적용이 되어야 할 것 같습니다

2023-08-28 09:53 UTC, unsignd commented on src/components/player/Default/Display.tsx
> +                <SimpleIconButton icon={PlayListSVG} />{" "}
의도된건가요?

2023-08-28 09:54 UTC, minibox24 commented on src/components/player/Default/Display.tsx
> +                <SimpleIconButton icon={PlayListSVG} />{" "}
헉

2023-08-29 14:18 UTC, minibox24 approved these changes

2023-08-29 17:02 UTC, choshinyoung approved these changes

2023-08-30 05:45 UTC, merged