플레이리스트 api 작업
wakmusic/wakmusic-pc pull request #164
Opened 2023-08-29 07:11 UTC by minibox24

## 개요

플레이리스트 api 작업

## 이슈

- #110 

## 작업 내용

- 일부 유튜브 플레이어 버그 수정
- 플레이리스트 API 작업
  - 리스트 생성
  - 리스트 가져오기
  - 리스트 순서 편집
  - 리스트에 담기
  - 리스트 상세
  - 리스트 재생

## 후추 필요 작업

- _**기존 리스트 관련 코드가 매우 더러워서 일단 api 작업(지금 이거) 마치고 @sandsunset이 리팩토링 해야함**_
- 스켈레톤 작업
- 토스트 메시지
- 개발 중 발견한 이슈들 처리
  - #162
  - #163

2023-08-29 12:34 UTC, jeewonSon requested changes
킹아~

2023-08-29 12:34 UTC, jeewonSon commented on src/components/modals/AddListModal/index.tsx
> +    const ok = await addSongToPlaylist(
먼가먼가 변수명을 좀 더 명확하게 할필요가 있다고 생각해용

2023-08-29 12:43 UTC, minibox24 commented on src/hooks/createListModal.ts
> +    originalTitle: string | undefined = undefined
openCreateListModal는 두 곳에서 사용됩니다

플리 만들떄, 플리 이름 수정할 때

이때인데 플리 이름을 수정할 때 originalTitle에 string가 들어가게 됩니다
그런데 플리 만들때는 originalTitle에 값을 넣을 필요가 없어서 저렇게 초기 값에 undefined를 넣어줬습니다

2023-08-30 05:45 UTC, kimbuckgur approved these changes

2023-08-30 06:03 UTC, merged