💄 디자인 수정
wakmusic/wakmusic-pc pull request #167
Opened 2023-08-29 16:05 UTC by minibox24

## 개요

디자인 수정

## 작업 내용

- 홈 화면에 동그라미들이 통통 튀어요
- 홈 화면에 글씨 마진 수정

2023-08-29 18:09 UTC, choshinyoung requested changes
프로그램 첫 시작 시에 원들이 날라가요 (리로드하면 정상 작동)

2023-08-29 18:10 UTC, choshinyoung reviewed
다른 크기의 창에서도 자연스럽게 보이면 좋을 것 같습니다

2023-08-30 05:44 UTC, kimbuckgur approved these changes
킹아입니다.

2023-08-30 09:35 UTC, choshinyoung approved these changes

2023-08-30 09:36 UTC, merged