⚡️ SelectSongs, CustomSongs 최적화
wakmusic/wakmusic-pc pull request #254
Opened 2023-09-10 07:45 UTC by sandsunset

## 개요

SelectSongs, CustomSongs 최적화

## 이슈

#163 #162 

## 작업 내용

- CustomSongs 드래그 앤 드롭과 관련된 여러 기능 최적화
- 곡 선택후 삭제시 선택된 곡에서 삭제된 곡 제거
- selectSongs의 index를 원본 songs와 동기화

2023-09-10 08:19 UTC, choshinyoung requested changes

2023-09-10 08:19 UTC, choshinyoung commented on src/hooks/selectSongs.ts
>    const selectCallback = (song: Song | Song[], index?: number) => {
이 함수의 song 파라미터가 두 종류의 타입을 받아서 타입별로 실행 코드가 완전히 다른데 두 함수로 분리하면 좋을 것 같습니다

2023-09-10 08:19 UTC, choshinyoung commented on src/hooks/selectSongs.ts
> +      if (targetOpposite != target && from[targetOpposite].songId === songId) {
!== 사용해주세요

2023-09-10 11:31 UTC, choshinyoung requested changes

2023-09-10 11:31 UTC, choshinyoung commented on src/hooks/selectSongs.ts
> +    (song: Song) => findIndex(selected, song.songId) != -1,
!== 사용해주세요

2023-09-10 11:48 UTC, choshinyoung requested changes
지금은 selectSongs.ts에서 OrderedSongType을 이용해서 index를 저장해 그 index대로 정렬해서 데이터를 저장하는데
이제는 플레이리스트에 중복 곡이 담길 수 없기 때문에
index를 저장하는 방식 대신 원본 songs 배열에서 index를 찾아서 정렬하는 방식이 더 깔끔할 것 같습니다

2023-09-10 11:51 UTC, sandsunset commented
> 지금은 selectSongs.ts에서 OrderedSongType을 이용해서 index를 저장해 그 index대로 정렬해서 데이터를 저장하는데 이제는 플레이리스트에 중복 곡이 담길 수 없기 때문에 index를 저장하는 방식 대신 원본 songs 배열에서 index를 찾아서 정렬하는 방식이 더 깔끔할 것 같습니다

그렇게 되면 매번 새로운 곡을 선택할때마다 기존에 있던 곡들의 인덱스를 모두 구하고 다시 정렬해야하기 때문에 인덱스를 미리 저장해놓는게 좋을거 같습니다

2023-09-10 11:52 UTC, sandsunset commented
새로운 곡을 선택하는것보다는 편집으로 곡들의 순서를 바꾸는 경우가 더 적어서 그렇게 생각했습니다

2023-09-10 11:57 UTC, choshinyoung commented
> > 지금은 selectSongs.ts에서 OrderedSongType을 이용해서 index를 저장해 그 index대로 정렬해서 데이터를 저장하는데 이제는 플레이리스트에 중복 곡이 담길 수 없기 때문에 index를 저장하는 방식 대신 원본 songs 배열에서 index를 찾아서 정렬하는 방식이 더 깔끔할 것 같습니다
> 
> 그렇게 되면 매번 새로운 곡을 선택할때마다 기존에 있던 곡들의 인덱스를 모두 구하고 다시 정렬해야하기 때문에 인덱스를 미리 저장해놓는게 좋을거 같습니다

선택할때마다 정렬하는 대신에 사용할때마다 (노래 담기, 재생목록에 추가 등) 따로 정렬해서 전달하는건 어떨까요

2023-09-10 12:00 UTC, sandsunset commented
> > > 지금은 selectSongs.ts에서 OrderedSongType을 이용해서 index를 저장해 그 index대로 정렬해서 데이터를 저장하는데 이제는 플레이리스트에 중복 곡이 담길 수 없기 때문에 index를 저장하는 방식 대신 원본 songs 배열에서 index를 찾아서 정렬하는 방식이 더 깔끔할 것 같습니다
> > 
> > 
> > 그렇게 되면 매번 새로운 곡을 선택할때마다 기존에 있던 곡들의 인덱스를 모두 구하고 다시 정렬해야하기 때문에 인덱스를 미리 저장해놓는게 좋을거 같습니다
> 
> 선택할때마다 정렬하는 대신에 사용할때마다 (노래 담기, 재생목록에 추가 등) 따로 정렬해서 전달하는건 어떨까요

그러면 selectSongs.ts 안에 정렬된 값을 반환하는 함수를 만들고 그 함수가 호출될때만 songs를 기준으로 정렬하는건 어떤가요

2023-09-10 12:19 UTC, choshinyoung commented
> > > > 지금은 selectSongs.ts에서 OrderedSongType을 이용해서 index를 저장해 그 index대로 정렬해서 데이터를 저장하는데 이제는 플레이리스트에 중복 곡이 담길 수 없기 때문에 index를 저장하는 방식 대신 원본 songs 배열에서 index를 찾아서 정렬하는 방식이 더 깔끔할 것 같습니다
> > > 
> > > 
> > > 그렇게 되면 매번 새로운 곡을 선택할때마다 기존에 있던 곡들의 인덱스를 모두 구하고 다시 정렬해야하기 때문에 인덱스를 미리 저장해놓는게 좋을거 같습니다
> > 
> > 
> > 선택할때마다 정렬하는 대신에 사용할때마다 (노래 담기, 재생목록에 추가 등) 따로 정렬해서 전달하는건 어떨까요
> 
> 그러면 selectSongs.ts 안에 정렬된 값을 반환하는 함수를 만들고 그 함수가 호출될때만 songs(원본)를 기준으로 정렬하는건 어떤가요

좋습니다

2023-09-11 10:00 UTC, choshinyoung commented on src/hooks/selectSongs.ts
> +  const findIndex = (from: Song[], songId: string) => {
findIndex 함수를 따로 만들어서 사용하시는 이유가 있나요?
js 내장 findIndex 함수와의 성능 차이는 크지 않을 것 같습니다

2023-09-11 10:06 UTC, sandsunset commented on src/hooks/selectSongs.ts
> +  const findIndex = (from: Song[], songId: string) => {
내장 findIndex는 첫번째 요소부터 차례대로 콜백 함수를 실행하면서 조건에 맞는 요소를 찾아내는데 아티스트 페이지나 재생목록처럼 전체 곡수가 많은 페이지에서 조금이라도 속도를 빠르게 하고자 따로 구현했습니다.

2023-09-11 16:13 UTC, choshinyoung requested changes
노래담기/재생목록추가 후 앱바가 비활성화되지 않습니다

2023-09-11 18:13 UTC, choshinyoung requested changes
플레이리스트 데이터가 변경된 후 첫 선택이 바로 취소되는 경우가 있습니다

2023-09-12 00:04 UTC, choshinyoung approved these changes
수고하셨습니다!!

2023-09-12 02:02 UTC, merged