✨ 크레딧 페이지
wakmusic/wakmusic-pc pull request #288
Opened 2023-09-20 19:09 UTC by choshinyoung

## 개요

✨ 크레딧 페이지

## 이슈

- #280 

## 작업 내용

- ✨ 크레딧 페이지

2023-09-21 03:22 UTC, cocoa-dev-1 requested changes
~~가사, 도움 주신 분들 칸을 클릭하면 에러가 발생합니다.~~
서버 오류 수정 완료

2023-09-21 04:00 UTC, cocoa-dev-1 approved these changes

2023-09-21 15:31 UTC, minibox24 commented on src/pages/teams/Teams.tsx
> +  }
그냥 null 하는 것보단 <PageLayout> <Container> 까지는 있어야지 로딩중에 창 깨지는 걸 막을 수 있을 것 같아요

2023-09-21 23:49 UTC, minibox24 commented on src/utils/utils.ts
> +};
constants로 옮기는거 어떨까요

2023-09-21 23:49 UTC, minibox24 commented on src/components/teams/Node.tsx
> +  node: React.FC;
통일성을 위해서 `import { ReactNode } from "react";` 로 변경해주세요

2023-09-22 03:29 UTC, choshinyoung commented on src/components/teams/Node.tsx
> +  node: React.FC;
React Element가 아닌 Function Component를 전달받는 파라미터입니다

2023-09-22 03:53 UTC, minibox24 approved these changes

2023-09-22 05:27 UTC, merged