✨ 로그인 모달
wakmusic/wakmusic-pc pull request #29
Opened 2023-07-09 03:33 UTC by minibox24

## 개요

로그인 모달 작업

## 작업 내용

- 로그인 모달 제작
- @state path 추가
- 여러 모달들을 위한 ModalPortal 제작
- recoil state 구조 제작

## 스크린샷

https://github.com/wakmusic/wakmusic-pc/assets/61264156/6823d63c-c39e-48ba-9ea7-1c7b7aeb7f6a

2023-07-09 03:49 UTC, choshinyoung approved these changes

2023-07-10 00:26 UTC, kimbuckgur requested changes
확인 오네가이시마스

2023-07-10 00:26 UTC, kimbuckgur commented on src/state/loginModal/hooks.ts
리액트 훅은 hooks폴더로 따로 빼두는게 좋을 것 같아요.

2023-07-10 00:26 UTC, kimbuckgur commented on src/components/modals/LoginModal.tsx
> +`;
안에 있는 속성을 그냥 글로벌에 있는 MdalContainer에 넣어도 문제없을 것 같은데용?

2023-07-10 02:36 UTC, minibox24 commented
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/28446fcf-e61b-4aa2-be23-7d3515096b0d)

프로필 선택 모달

2023-07-10 03:17 UTC, kimbuckgur approved these changes
수고하셨습니다. 근데 제가 단 코멘트 확인 한번 만 해주시면 감사하겠습니다! 짱짱

2023-07-10 09:45 UTC, merged