:sparkles: 탭 바 컴포넌트
wakmusic/wakmusic-pc pull request #31
Opened 2023-07-09 09:56 UTC by sandsunset

## 개요

탭 바 글로벌 컴포넌트

## 이슈

#30 

## 작업 내용

- 탭 바 컴포넌트 제작
- 중첩 라우팅 또는 쿼리 파라미터를 사용하는 상황에서 적용할 수 있도록 작업했습니다

## 스크린샷

https://github.com/wakmusic/wakmusic-pc/assets/61652299/1295c478-86f1-4657-913b-ca5e49bd6319

2023-07-09 14:15 UTC, minibox24 requested changes

2023-07-09 14:15 UTC, minibox24 commented on src/components/globals/Tab.tsx
> +        `
텍스트 컬러가 `gray900` 입니다!

2023-07-09 14:15 UTC, minibox24 commented on src/components/globals/TabBar.tsx
> +      const _props: TabProps = children[i].props;
`children.forEach`를 사용하는게 좀 더 직관적이지 않을까요..?

2023-07-09 14:19 UTC, minibox24 requested changes

2023-07-09 14:19 UTC, minibox24 commented on src/components/globals/TabBar.tsx
> +
디버깅용 코드라면 제거 부탁드려요

2023-07-09 23:17 UTC, sandsunset commented
해결했습니다 😋

2023-07-10 00:34 UTC, minibox24 requested changes

2023-07-10 00:34 UTC, minibox24 commented on src/components/globals/TabBar.tsx
> +      i++;
`.forEach(child, index)` 로 따로 `i` 변수를 만들지 않고 index로 관리하는게 낫지 않을까요?

2023-07-10 08:26 UTC, minibox24 requested changes

2023-07-10 08:26 UTC, minibox24 commented on src/components/globals/Tab.tsx
> +      return searchParams.get(key) === value;
나중에 제작할 검색 페이지에서는 search params에 `type` 말고도 `query`도 생길 듯 한데 일단 여기만 봐서는 여러개의 search params를 대응하지 못하는 것으로 보여요

2023-07-11 00:33 UTC, minibox24 reviewed
혹..시 모든 Tab들을 constant로 관리하니까 `<TabBar tabs={ /* 여기에 데이터를 넣는 식으로  */ } />` 진행해도 되지 않을까요?

2023-07-11 00:35 UTC, minibox24 requested changes

2023-07-11 00:35 UTC, minibox24 commented on src/components/globals/TabBar.tsx
> +    `}
여기는 최적화를 위해서 `<Indicater style={{ marginLeft: `${target * 54}px` }}>` 이런식으로 하는게 좋을 것 같아요

2023-07-11 00:44 UTC, sandsunset commented on src/components/globals/TabBar.tsx
> +    `}
넵

2023-07-11 02:04 UTC, sandsunset commented
> 혹..시 모든 Tab들을 constant로 관리하니까 `<TabBar tabs={ /* 여기에 데이터를 넣는 식으로 */ } />` 진행해도 되지 않을까요?

![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/32f1746b-f6b1-4c44-a205-50bf1b2c4923)

Search 같은 경우는 탭에 유동적인 데이터도 들어가서요 괜찮을까요?

2023-07-11 02:06 UTC, sandsunset commented
일단 TabBar에 tabs로 데이터를 넣는 방식도 구현해보겠습니다

2023-07-11 13:42 UTC, minibox24 approved these changes
리뷰가 정말 많았는데..ㅋㅋ 수고하셨습니다!!

2023-07-11 13:43 UTC, choshinyoung approved these changes

2023-07-11 13:53 UTC, merged