chart 페이지 임시 완성
wakmusic/wakmusic-pc pull request #34
Opened 2023-07-12 00:02 UTC by kimbuckgur

## 개요

어떤 작업인가요?

chart 페이지 퍼블리싱 및 뮤직 컨트롤러 개발
![image](https://github.com/wakmusic/wakmusic-pc/assets/80795917/179363b0-3b2e-4180-b9e0-0cab168b251a)

## 이슈

#21

## 작업 내용

- chart 페이지 퍼블리싱
- 뮤직 컨트롤러 퍼블리싱

## 스크린샷

![image](https://github.com/wakmusic/wakmusic-pc/assets/80795917/b79e274e-842b-41b9-91a4-ed9e8e0f7fc2)

2023-07-12 15:11 UTC, minibox24 requested changes

2023-07-12 15:11 UTC, minibox24 commented on src/components/chart/MusicList.tsx
> +    props.select ? colors.blueGray200 : "rgb(0,0,0,0)"};
이런식으로 하기보다는 아래 코드가 더 이쁘지 않을까 싶어요

```ts
  ${({ select }) =>
    select &&
    css`
      background-color: ${colors.blueGray200};
    `}
```

2023-07-12 15:11 UTC, minibox24 commented on src/components/chart/MusicList.tsx
> +    <Wrapper select={false}>
HTML의 디폴트? 내장? props랑 겹쳐서 콘솔에 오류가 뜨네요.. `$select`로 prop명을 바꾸면 좋을 것 같아요

2023-07-12 15:14 UTC, minibox24 reviewed
뮤직 컨트롤러쪽을 계속 살펴보긴 했는데 지금 구현해주신 방법은 영 좋지 않은 방법이라는 생각이 드네요..ㅠㅠ

제가 간단히 생각해본건데 이런 느낌은 어떨까요?

```tsx
<MusicController selected={3}>
  <SelectAll onClick={ } />
  <Add onClick={ } />
  <AddPlaylist onClick={ } />
  <Play onClick={ } />
</MusicController>
```

이런식으로 각각 뮤직 컨트롤러가 필요한 곳에서 버튼들을 유동적으로 추가하는거죠

2023-07-14 13:40 UTC, minibox24 requested changes

2023-07-14 13:40 UTC, minibox24 commented on src/components/globals/musicControllers/MusicControllerBase.tsx
> +          <T4Bold>{count}</T4Bold>
`#2760F4` (`colors.sub`) 입니다!

2023-07-14 15:01 UTC, minibox24 requested changes

2023-07-14 15:01 UTC, minibox24 commented on src/components/globals/musicControllers/MusicControllerBase.tsx
> +  }
굳,,이 이렇게 하기 보다는 ` <T4Bold color={colors.sub}>{count}</T4Bold>` 는 어떨까요..?

2023-07-14 16:06 UTC, minibox24 approved these changes
수고하셨습니다!

2023-07-14 16:57 UTC, cocoa-dev-1 approved these changes

2023-07-14 19:03 UTC, choshinyoung approved these changes

2023-07-15 03:40 UTC, merged