최신 음악 페이지 퍼블리싱 작업
wakmusic/wakmusic-pc pull request #47
Opened 2023-07-16 11:37 UTC by kimbuckgur

## 개요

![image](https://github.com/wakmusic/wakmusic-pc/assets/80795917/7bf4974c-65e6-42cc-bfbf-ef5c4f6aac64)

## 이슈

#41

## 작업 내용

- 최신 음악 페이지 퍼블리싱

2023-07-16 16:39 UTC, minibox24 requested changes
`develop` 머지해서 업데이트된 스크롤바 적용해주세요! (+ 더미데이터 이용해서 데이터 들어가는서 살짝만 구현해주셔도 좋을 것 같아요)

2023-07-19 12:01 UTC, minibox24 requested changes
새 스크롤바 적용해주세요!!

설명은 여기 있습니다

https://github.com/wakmusic/wakmusic-pc/pull/45#issue-1806457571

2023-07-19 14:23 UTC, choshinyoung commented
위치가 맞지 않는 것 같습니다
![image](https://github.com/wakmusic/wakmusic-pc/assets/50575654/61f4cb88-bcd7-4e62-b201-920d7babd222)

2023-07-20 02:37 UTC, choshinyoung commented on src/components/new/FunctionSection.tsx
> +import tabType from "../../templates/tabType";
`@templates`로 쓰는게 깔끔할 것 같습니다

2023-07-20 02:37 UTC, choshinyoung commented on src/components/new/FunctionSection.tsx
> +const TestCategory = styled.div`
혹시 Test 컴포넌트들은 일부러 남겨두신건가요?

2023-07-22 05:53 UTC, choshinyoung commented on src/constants/IconButton.ts
> +import iconButtonType from "../types/iconButtonType";
여기도 `@templates`로 바꾸셔야될거같습니다

2023-07-22 06:06 UTC, choshinyoung approved these changes

2023-07-23 02:56 UTC, minibox24 requested changes

2023-07-23 02:56 UTC, minibox24 commented on src/constants/tabs.ts
> +  { text: "고맴", to: { type: "gomem" } },
`고멤` 으로 수정해주세요!

2023-07-29 05:10 UTC, minibox24 requested changes

2023-07-29 05:10 UTC, minibox24 commented on src/main.tsx
>              <Route path="/user/*" element={<User />} />
똑같은게 두개 있네요
위에꺼 하나는 지우셔야할 것 같아요

2023-07-29 05:31 UTC, kimbuckgur commented on src/main.tsx
>              <Route path="/user/*" element={<User />} />
컨플릭트 해결하면서 남아있었나 보네요

2023-07-29 05:32 UTC, minibox24 approved these changes

2023-07-29 05:33 UTC, merged