검색 페이지 작업
wakmusic/wakmusic-pc pull request #48
Opened 2023-07-16 16:03 UTC by unsignd

## 개요
<img width="1362" alt="Screenshot 2023-07-17 at 12 57 40 AM" src="https://github.com/wakmusic/wakmusic-pc/assets/63943594/a1c865f0-3365-4ca5-ac65-4dbe43b47a4b">

검색 시 나타나는 결과 페이지를 작업했습니다.
또한 몇몇 기능들을 개선시켰습니다.

## 이슈

#36 

## 작업 내용

- 검색 시 결과로 나오는 결과 없음 페이지와 카테고리별 결과 페이지를 작업
- 헤더 검색 인풋필드 색 변경 (샴퓨님 요청)
- 헤더 검색 인풋필드에서 검색 시 쿼리를 초기화시키는 코드 제거 (샴퓨님 요청)

2023-07-16 16:47 UTC, minibox24 requested changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/70f8a42f-aa55-4ad2-9041-65c43d9c0e3e)

알 수 없는 가로 스크롤바가 있습니다

2023-07-16 16:48 UTC, minibox24 requested changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/81ba3c36-a0a2-4888-9665-9a636f949ec3)

업데이트된 스크롤바 적용 부탁드립니다

2023-07-17 03:52 UTC, choshinyoung commented on src/components/search/Result.tsx
> +                    likeList[item.songId].toString().length >= 5
#50 적용해서 수정해주시면 좋을 것 같습니다!

2023-07-17 10:53 UTC, kimbuckgur requested changes
수고많으십니다 조금 만 더 수고해주세요!! 감사합니다!!

2023-07-17 10:53 UTC, kimbuckgur commented on src/components/globals/Track.tsx
> +  overflow: hidden;
const TrackStyle = css`
  max-width: 206px;
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
`

const TrackTitle = styled(T5Medium)`
  ${TrackStyle} ;
  color: ${colors.gray700};
`;

const TrackArtist = styled(T6Medium)`
  ${TrackStyle};
  color: ${colors.blueGray500};
`

이렇게 처리하는거는 어떨까요?

2023-07-17 10:53 UTC, kimbuckgur commented on src/components/search/Result.tsx
> +                  )
이 부분은 함수로 빼고 삼항 연산자 보다는 if문을 써서 좀 더 가독성이 좋게 바꾸는게 좋을 것 같습니다.

2023-07-17 10:53 UTC, kimbuckgur commented on src/pages/search/Search.tsx
> +
자주  사용할 것 같은 타입은 src/types  폴더에 넣어놓고 두고두고 사용하는게 좋을 것 같아용

2023-07-17 10:53 UTC, kimbuckgur commented on src/pages/search/Search.tsx
> +      | "training";
as 가 네이버 개발자께서 말씀하시길 약간 커파일러 속이기?? 느낌이라서 get한 다음에 if 문으로 한번 검사 한후에 진행시키는거 어떨까요?

2023-07-17 10:53 UTC, kimbuckgur commented on src/pages/search/Search.tsx
> +  const [tab, setTab] = useState<"all" | "songs" | "artists" | "training">(
여기 리터럴로 넣은 타입을 type tabsTypes = "all" | "songs" | "artists" | "training" 로 Search 컴포넌트 위에 선언해두고 쓰면 좋을 듯 싶습니다

2023-07-17 10:53 UTC, kimbuckgur commented on src/components/search/SongSection.tsx
> +      <Text left={664}>{count}</Text>
둘을 div로 묶고 그 div에다가 margin-right를 주는게 더 좋을 듯 합니다
이거는 제 주관적인 생각입니다.

2023-07-17 12:09 UTC, unsignd commented
> 수고많으십니다 조금 만 더 수고해주세요!! 감사합니다!!

감사합니다! 하나하나 고쳐보는 즐거운 리라이팅 시간을 가져보겠습니다.. 😂

2023-07-17 12:33 UTC, minibox24 requested changes
코드 내에서 모든 조교를 `remix`로 통일해주세요

2023-07-18 11:36 UTC, minibox24 requested changes
현재 모든 데이터들 처리가 Result 컴포넌트에서 이뤄집니다 분리가 좀 필요해보여요

all 탭 컴포넌트, 그 외 탭들로 2개 컴포넌트로 분리하면 좋을 것 같네요

이거 하시면 다음 리뷰 해드릴게요 화이팅

2023-07-18 12:44 UTC, minibox24 approved these changes
수고하셨습니다!!!

2023-07-18 12:54 UTC, kimbuckgur approved these changes
수고많으셨습니다

2023-07-18 13:09 UTC, sandsunset requested changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/b8cb39c8-ba7f-44ed-98cd-42f263a710fc)

브라우저 창에서 들어가면 검색시에 드롭바가 기본 브라우저랑 겹치는거 같아요 이거까지 수정해주실 수 있나요?

2023-07-18 13:37 UTC, sandsunset commented on src/components/search/SongSection.tsx
> +  }
Track의 스타일을 가르키는거 같은데 좀 더 알아보기 쉽게 Track.tsx안으로 옮기면 좋을거 같아요

2023-07-18 14:08 UTC, sandsunset approved these changes

2023-07-18 14:40 UTC, choshinyoung requested changes

2023-07-18 14:40 UTC, choshinyoung commented on src/utils/formatting.ts
> +export function dateToText(date: number): string {
함수 이름을 다른 함수에 맞춰서 formatDate()로 바꿔주세요

2023-07-18 14:40 UTC, choshinyoung commented on src/components/search/Result.tsx
> +  else return <NotFound />;
`else`는 제거하는게 더 깔끔할 것 같습니다

2023-07-18 14:40 UTC, choshinyoung commented on src/pages/search/Search.tsx
> +type tabsTypes = "all" | "song" | "artist" | "remix";
타입은 @templates에 모아두는게 좋을 것 같습니다

2023-07-18 14:40 UTC, choshinyoung commented on src/components/search/Result.tsx
> +  tab: "all" | "song" | "artist" | "remix";
`Search.tsx`에서 선언된 `tabsTypes` 타입을 재사용하는게 좋을 것 같습니다

2023-07-18 15:02 UTC, merged