플레이어 컴포넌트
wakmusic/wakmusic-pc pull request #56
Opened 2023-07-21 08:55 UTC by choshinyoung

## 개요

플레이어 컴포넌트 제작

## 이슈

#19 

## 스크린샷

![image](https://github.com/wakmusic/wakmusic-pc/assets/50575654/2deac402-22d4-4a41-89fa-254593793dd2)

2023-07-21 11:49 UTC, kimbuckgur requested changes
리뷰 화긴오네가이시마스

2023-07-21 11:49 UTC, kimbuckgur commented on src/components/player/Controller.tsx
> +    setIsPlaying(!isPlyaing);
useReducer을 사용하는거는 어떨까요?

2023-07-21 11:49 UTC, kimbuckgur commented on src/components/player/Controller.tsx
> +            : RepeatOffSvg
가독성이 떨어지는 것 같습니다 함수로 따로 빼는게 좋을 거 같습니다 그리고 함수로  뺏을때는 if문으로 처리하는게 좋을 것 같습니다.

2023-07-21 11:49 UTC, kimbuckgur commented on src/components/player/Lyrics.tsx
> +      : lyrics.findIndex((line) => current < line.start) - 1;
여기도 if 문으로 처리  부탁드리곘습니다.

2023-07-21 11:49 UTC, kimbuckgur commented on src/components/player/Playlist.tsx
> +  const [cursorIndex, setCursorIndex] = useState(0);
음... state가 너무 많네요 객체로 만들어서 하나의 스테이트로 관리하는게 좋을 것 같아요

2023-07-21 11:49 UTC, kimbuckgur commented on src/components/player/Visual.tsx
> +  const img = `https://i.ytimg.com/vi/${songId}/hqdefault.jpg`;
이거 생각을 많이 해봤는데 이렇게 처리하는거 보다 id 넣으면 url 리턴하는 함수를 util에다가 만드는게 좋을 것 같네용 제가 미니 박스님께 여쭤보고 그렇게 하자고 하시면 이거 머지 된 다음에 한번 수정해주세용

2023-07-21 11:53 UTC, minibox24 reviewed
https://github.com/wakmusic/wakmusic-pc/assets/61264156/0c02f4bf-0d74-4773-8f17-4cb048c60024

가사를 켜면 무조건 맨 위에서 스크롤되는 방식으로 되던데 살짝 유저 경험이 떨어질 것 같은 느낌이 듭니당

2023-07-21 15:00 UTC, choshinyoung commented on src/components/player/Controller.tsx
> +    setIsPlaying(!isPlyaing);
recoil 사용으로 변경했는데 확인 부탁드립니다

2023-07-21 15:47 UTC, minibox24 requested changes
몇몇 곡의 경우에는 가사에 줄바꿈이 있습니다 지원바람

2023-07-21 16:26 UTC, unsignd requested changes

2023-07-21 16:26 UTC, unsignd commented on src/components/player/Lyrics.tsx
> +        )}
```tsx
        {lyrics.map((line, i) => {
          const Line = i === getIndex() ? CurrentLine : DefaultLine;

          return (
            <Line
              key={i}
              color={colors.blueGray25}
              onClick={() => onLineClick(i)}
            >
              {line.text}
            </Line>
          );
        })}
```

위 방식처럼 코드를 변경하면 가독성이 더 향상될 것 같습니다

2023-07-21 16:38 UTC, unsignd approved these changes

2023-07-21 17:24 UTC, minibox24 approved these changes
수고하셨습니다!! wakKa

2023-07-22 04:10 UTC, kimbuckgur commented on src/components/player/Controller.tsx
> +    setIsPlaying(!isPlyaing);
킹아 입니다

2023-07-22 04:11 UTC, kimbuckgur approved these changes
킹아 입니다 수고 많으십니다!!

2023-07-22 04:13 UTC, merged