✨ : static Util 개발
wakmusic/wakmusic-pc pull request #59
Opened 2023-07-22 05:21 UTC by kimbuckgur

## 개요
static API들을 사용하기 용이 하게 utill 함수로 작업

## 이슈

#57

## 작업 내용

- static api들 모듈화

## 스크린샷
![image](https://github.com/wakmusic/wakmusic-pc/assets/80795917/ee734898-10a0-4853-8ee0-344c387cf58c)

2023-07-22 05:49 UTC, choshinyoung commented on src/utils/staticUtill.ts
> +    URL = `${staticURL}/artist/${type}/${id}.jpg`;
if문 안에서 따로 return하는게 깔끔할 것 같습니다

2023-07-22 05:50 UTC, kimbuckgur commented on src/utils/staticUtill.ts
> +    URL = `${staticURL}/artist/${type}/${id}.jpg`;
옛설

2023-07-22 05:52 UTC, choshinyoung approved these changes

2023-07-23 02:49 UTC, minibox24 requested changes

2023-07-23 02:49 UTC, minibox24 commented on src/utils/staticUtill.ts
> +const staticURL = "https://static.wakmusic.xyz/static/";
여기는 `.env`로 빼는게 좋을 것 같습니다

2023-07-31 13:24 UTC, choshinyoung approved these changes

2023-08-01 11:14 UTC, cocoa-dev-1 approved these changes

2023-08-01 11:40 UTC, merged