✨ 플레이어 비주얼모드 제작
wakmusic/wakmusic-pc pull request #61
Opened 2023-07-22 19:00 UTC by choshinyoung

## 개요

플레이어 비주얼모드 제작

## 이슈

#58 

## 작업 내용

- 플레이어 컴포넌트에 recoil state 적용
- 플레이어 컴포넌트 파일의 디렉토리를 `Default`와 `Visual`로 분리
- 플레이어 비주얼모드 제작

## 스크린샷

![image](https://github.com/wakmusic/wakmusic-pc/assets/50575654/ff392e45-5c44-4e02-bad1-a52133c59854)
![image](https://github.com/wakmusic/wakmusic-pc/assets/50575654/8f655769-e772-493b-8dc0-1d9fe800ca6d)

2023-07-23 02:38 UTC, minibox24 commented on src/components/player/Visual/Header.tsx
> +      )}
디폴트 헤더에서 중복되는 부분인데 따로 글로벌 컴포넌트로 빼도 되지 않을까요?

2023-07-23 13:46 UTC, minibox24 approved these changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/eec42fbd-e671-4508-9b66-cfc08ac982ef)

2023-07-26 13:48 UTC, sandsunset approved these changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/74c0125d-c32b-4c30-9eab-c839be340e5c)

배경에 background-repeat 속성이 적용되어 있는거 같습니다
캡쳐는 웹에서 비주얼모드로 들어간 상태에서 가로 길이를 줄이고 촬영했습니다

2023-07-26 13:50 UTC, sandsunset requested changes
실수로 approve로 리뷰를 눌렀습니다 죄송합니다..!

2023-07-28 09:10 UTC, minibox24 approved these changes

2023-07-29 04:50 UTC, sandsunset approved these changes

2023-07-29 18:42 UTC, merged