✨ 드래그 앤 드롭 기능 구현
wakmusic/wakmusic-pc pull request #62
Opened 2023-07-23 14:02 UTC by sandsunset

## 개요

보관함 페이지의 드래그 앤 드롭을 통한 내 리스트 순서 수정 기능 제작

## 작업 내용

- 보관함 페이지의 내 리스트 순서 수정 기능을 작업했습니다
- 플레이리스트 template을 추가하고 song template을 따로 분리했습니다

## 스크린샷

https://github.com/wakmusic/wakmusic-pc/assets/61652299/26079341-af23-4051-bf3e-9f2a2698678f

2023-07-23 14:06 UTC, sandsunset commented on src/components/user/playlist/PlaylistItem.tsx
> +
애니메이션을 넣어보려고 시도한 흔적인데...
만약 드래그 앤 드롭에 애니메이션을 넣지 않게 된다면 훨씬 간단하고 빠른 방법으로 수정하겠습니다

2023-07-26 10:57 UTC, choshinyoung approved these changes

2023-07-26 10:59 UTC, minibox24 requested changes

2023-07-26 10:59 UTC, minibox24 commented on src/components/user/header.tsx
파일명이 대문자여야할 것 같습니다

2023-07-28 06:55 UTC, minibox24 approved these changes

2023-07-28 07:32 UTC, merged