✨ 마이페이지 레이아웃 구현 완료
wakmusic/wakmusic-pc pull request #66
Opened 2023-07-24 16:30 UTC by unsignd

## 개요

마이페이지 (/mypage)의 css 디자인을 완료하고, 기본적인 레이아웃을 잡았습니다.

## 이슈

#64

## 작업 내용

- 마이페이지 레이아웃 디자인을 완성했습니다.

2023-07-26 10:08 UTC, minibox24 requested changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/fd680145-8ad7-431d-9fef-ea6d7d89aced)

DevTools에 뜨는 오류 2개 처리 부탁드립니다

2023-07-26 10:18 UTC, minibox24 requested changes

2023-07-26 10:18 UTC, minibox24 commented on src/pages/mypage/MyPage.tsx
> +import Panchi from "@assets/dummy/panchi.png";
에셋에 커밋하신건 리버트하시고 노션 참고해서 api에서 이미지 불러오는걸로 수정해주세요

2023-07-27 13:59 UTC, minibox24 requested changes

2023-07-27 13:59 UTC, minibox24 commented on src/main.tsx
> -            <Route path="/mypage" element={<MyPage />} />
이걸... 왜 지우신거죠...????

2023-07-27 14:13 UTC, minibox24 requested changes

2023-07-27 14:13 UTC, minibox24 commented on src/pages/mypage/MyPage.tsx
> +        />
코드를 꼭 저렇게 작성해야 한다면

```tsx
        <Block
          title="문의하기"
          description={`이용 관련 문의를 등록하시면
                        빠른 시일 내에 처리하겠습니다.`}
          svg={<QuestionSVG />}
        />
```

이렇게 작성하는게 좀 더 깔끔해지지 않을까 싶어요

2023-07-27 14:22 UTC, minibox24 approved these changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/344d9154-05fc-44e0-9164-baffd05a1b34)

2023-07-27 15:50 UTC, choshinyoung approved these changes

2023-07-28 04:03 UTC, merged