대부분의 페이지 리팩토링
wakmusic/wakmusic-pc pull request #67
Opened 2023-07-29 14:27 UTC by minibox24

## 개요

대부분의 페이지 리팩토링

## 이슈

#55

## 작업 내용

- 편한 css 디버깅을 위해서 styled-component macro 적용
  - ![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/c777f526-d890-479a-b900-641f1373a60c)
  - 클래스명에 styled component 변수 이름이 들어갑니다
- `@layouts` path 추가
  - 기존 공통 컴포넌트들에서 레이아웃들을 담당하던 컴포넌트들을 따로 뺐습니다
- `PageItemContainer` 컴포넌트 제작
  - 스크롤바 컴포넌트가 있지만 일관성을 위해서 스크롤바를 래핑하는 컴포넌트를 새로 또 제작하였습니다
- `SongItem` 컴포넌트 제작
  - 많은 페이지에서 사용되는 노래 정보 컴포넌트들을 재사용 가능하게 제작 후 뺐습니다
- `GuideBar` 컴포넌트 제작
  - 몇몇 페이지에서 사용되는 그 모시깽이 컴포넌트를 재사용 가능하게 제작하였습니다
- `UpdatedText` 컴포넌트 제작
  - "00월 00일 오전 00시 업데이트" 글씨 뜨는 컴포넌트를 뺐습니다
- `/chart`로 접속하면 자동으로 기본값인 `/chart?type=hourly`으로 리다이렉트 되게 하였습니다
- 모든 파일에 린팅을 돌렸습니다

2023-07-29 18:23 UTC, choshinyoung approved these changes

2023-07-30 06:37 UTC, unsignd commented on src/components/globals/GuideBar.tsx
> +
전체적으로 hex코드를 color.ts에 있는 변수명으로 변경하면 가독성이 오를 것 같습니다!
투명도가 적용된 rgba같은 경우에도 ${colors.white}66 이런식으로 변경이 가능하니 만일 이 방법이 낫다고 생각하시면 참고해서 수정 부탁드립니다

2023-07-30 07:00 UTC, unsignd approved these changes
❤️

2023-07-30 07:16 UTC, sandsunset requested changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/b71280ca-aba2-4858-8a6e-1d64fb3e99c0)

![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/20d179bf-926a-4457-9729-f23a5f607398)

가이드 바와 노래 정보 컴포넌트 사이 간격이 디자인과 맞지 않는거 같습니다

2023-07-30 07:38 UTC, sandsunset requested changes

2023-07-30 07:38 UTC, sandsunset commented on src/components/chart/FunctionSection.tsx
> +        })}
여기서는 return을 빼도 될거 같습니다

2023-07-30 10:28 UTC, sandsunset commented
![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/13e82ba7-c953-49dd-a1cc-11249ccdb15e)
![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/d0bfdbb4-0057-479a-aa6e-1135b3843c39)

구현된 노래정보 UI가 디자인보다 썸네일이 딱 1픽셀정도 더 오른쪽으로 위치해 있는거 같습니다..! 😅

2023-07-30 10:54 UTC, sandsunset approved these changes
수고하셨습니다😋

2023-07-30 10:55 UTC, merged