✨ 분리 모드
wakmusic/wakmusic-pc pull request #68
Opened 2023-07-30 03:46 UTC by minibox24

## 개요

플레이어 분리 모드

## 작업 내용

- 플레이어 분리 모드 제작

## 스크린샷

![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/c29ae56b-88a8-4c4c-b9b2-3c29b56890f3)

2023-07-31 10:40 UTC, choshinyoung commented
![image](https://github.com/wakmusic/wakmusic-pc/assets/50575654/407a9a96-ac53-4ee2-bac1-16a8507ac4bc)
분리모드에서 왁뮤 로고를 클릭해도 default 모드로 바뀌지 않습니다

2023-07-31 10:41 UTC, choshinyoung requested changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/50575654/1111a95a-b748-4fb6-84be-97fb21e420dd)
분리모드에서 default로 전환한 후 헤더의 right arrow버튼을 클릭하면 default 모드가 유지되며 빈 페이지가 나옵니다

2023-07-31 10:48 UTC, choshinyoung commented
가사모드가 켜진 상태에서의 비주얼모드 전환 애니메이션이 어색해보이는데 이건 의도하신건가요

2023-07-31 11:03 UTC, choshinyoung requested changes
비주얼모드의 가사모드에서 가사 부분의 패딩이 디자인과 일치하지 않습니다.
또한 LyricsMode.tsx에서 extraPadding은 제거해도 될것같습니다

2023-07-31 11:45 UTC, sandsunset requested changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/7875c5d3-bf2c-4485-9817-343f035456ff)

분리 모드 상태에서 가로 길이 조절을 막아야 할거 같습니다

2023-07-31 11:49 UTC, minibox24 commented
> ![image](https://user-images.githubusercontent.com/61652299/257208572-7875c5d3-bf2c-4485-9817-343f035456ff.png)
> 
> 분리 모드 상태에서 가로 길이 조절을 막아야 할거 같습니다

코드상 되어있긴 해요

2023-07-31 11:49 UTC, sandsunset commented
분리 모드를 키면 처음 창 크기가 줄어들고 아주 잠깐 동안 원래 있던 페이지의 내용이 겹쳐보여 깜빡이는것처럼 보이는데 수정해주시면 좋을거 같습니다

2023-07-31 12:05 UTC, unsignd requested changes

2023-07-31 12:05 UTC, unsignd commented on src/components/player/Default/Display.tsx
> +    >
styled-component가 있는데 인라인 스타일링은 자제하는게 낫지 않을까 생각합니다!

2023-07-31 12:53 UTC, kimbuckgur submitted a review, later dismissed
리뷰 답변오네가이시마스~

2023-07-31 12:53 UTC, kimbuckgur commented on src/components/player/Default/Display.tsx
>    const img = `https://i.ytimg.com/vi/${song.songId}/hqdefault.jpg`;
나중에 개발 후반부에 static으로 한번에 변경해용

2023-07-31 15:04 UTC, minibox24 commented on src/components/globals/ControlBar.tsx
> +            : DivideSVG // 그 외에는 분리만 가능
가독성 우려해서 주석 달아놨는데 저는 이대로가 괜찮다고 봅니다

2023-07-31 15:29 UTC, minibox24 commented
> 가사모드가 켜진 상태에서의 비주얼모드 전환 애니메이션이 어색해보이는데 이건 의도하신건가요

제 한계입니다

가능하다면 대신 수정 부탁드립니다

2023-07-31 16:03 UTC, unsignd approved these changes

2023-07-31 16:17 UTC, choshinyoung submitted a review, later dismissed
`LyricsMode.tsx`의 LyricsContainer의 높이와 마진이 디자인과 일치하지 않습니다

2023-08-01 01:44 UTC, kimbuckgur commented on src/components/globals/ControlBar.tsx
> +            : DivideSVG // 그 외에는 분리만 가능
팀장님의 뜻대로!

2023-08-03 15:43 UTC, sandsunset approved these changes

2023-08-03 17:10 UTC, merged