Feature/playlistinfo
wakmusic/wakmusic-pc pull request #69
Opened 2023-07-30 13:35 UTC by sandsunset

## 개요

플레이리스트 페이지 UI 구현, 사소한 코드 리펙토링

## 작업 내용

- 플레이리스트 페이지 UI를 구현했습니다
- GNB 하이라이트가 중첩 라우팅에서 적용되지 않던 문제점을 수정했습니다
- 내 리스트 파일명들을 조금 더 직관적으로 수정했습니다
- 보관함 페이지를 위한 텍스트 버튼 글로벌 컴포넌트를 제작했습니다

## 스크린샷

![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/19544672-98ce-4099-a263-c0ece021aab7)

2023-07-30 16:24 UTC, minibox24 requested changes
메인 페이지의 추천 리스트 페이지도 구현해주세요

`리스트 만들기`, `리스트 가져오기`, 플레이리스트 공유 모달들을 연결해주세요

2023-07-31 12:01 UTC, unsignd requested changes

2023-07-31 12:06 UTC, unsignd approved these changes

2023-07-31 12:40 UTC, choshinyoung approved these changes

2023-07-31 13:19 UTC, kimbuckgur requested changes
코드리뷰 확인 오네가이시마수

2023-07-31 13:19 UTC, kimbuckgur commented on src/components/user/Header.tsx
> +  const [isLikesEditMode, setLikesEditMode] = useRecoilState(likesState);
이 부분 여태까지 미니박스님이 사용하던 recoil 방식과 다른 거 같은데 [여기](https://github.com/wakmusic/wakmusic-pc/blob/develop/src/hooks/loginModal.ts) 참고해서 수정 부탁드립니다.

2023-07-31 13:19 UTC, kimbuckgur commented on src/components/user/Header.tsx
> +    else setLikesEditMode(!isLikesEditMode);
if 문을 사용할때는 중괄호({})를 사용하는게 가독성이 좋습니다!

2023-07-31 13:19 UTC, kimbuckgur commented on src/components/user/Header.tsx
> +  const toggleEditMode = useCallback(() => {
굳이 콜백을 쓸만큰 무거워 보이지 않습니다! 
오히려 useCallback을 쓰는게 더 손해일 것 같아요.

(말예쁘게 하고 싶었는데 어떻게 써야 예쁜건지 잘모르겠습니다...)

2023-07-31 13:19 UTC, kimbuckgur commented on src/pages/user/User.tsx
>            <Route path="/likes" element={<Likes />} />
이건 궁금한건데 여기에 Route를 설정하신 이유가 있으신가요?

2023-07-31 14:12 UTC, sandsunset commented
GNB에서 탭 이외의 페이지로 이동했을때 가장 마지막으로 있던 탭의 하이라이트를 유지하는 기능도 추가로 구현했습니

2023-07-31 14:14 UTC, sandsunset commented on src/pages/user/User.tsx
>            <Route path="/likes" element={<Likes />} />
보관함 페이지 내에서 탭으로 이동하는 중첩 라우팅을 적용하기 위해 User.tsx 내부에 Route를 설정했습니다

2023-07-31 14:32 UTC, sandsunset commented on src/components/user/Header.tsx
> +  const toggleEditMode = useCallback(() => {
아닙니다 덕분에 좋은 정보 알아갑니다! 😋

2023-07-31 14:33 UTC, sandsunset commented on src/pages/user/Mylist.tsx
> +        <IconButton icon={Import}>리스트 가져오기</IconButton>
![image](https://github.com/wakmusic/wakmusic-pc/assets/61652299/4306019e-8815-4784-8f2d-ddcb6466e189)

onClick 시에 모달 훅을 이용해야 해서 완벽하게 constants에 데이터를 담고 동적으로 관리하기에는 어려울거 같아서요
map을 돌리면서 추가로 Mylist.tsx 안에서 훅을 따로 처리하도록 해서 구현할까요?

2023-07-31 15:33 UTC, minibox24 requested changes
![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/ea275cad-71ad-4597-8b74-5ec1e98d3d07)

확인 부탁드립니다

2023-07-31 15:41 UTC, minibox24 requested changes

2023-07-31 15:41 UTC, minibox24 commented on src/pages/user/Mylist.tsx
>    const [isEditMode] = useRecoilState(myListState);
여기를 포함해서 코드에서 직접적으로 recoil state를 사용하는 부분들 처리해주세요!

2023-07-31 15:41 UTC, minibox24 requested changes
플레이리스트 페이지에서 공유 버튼을 눌렀을 때 모달이 나오지 않습니다

2023-07-31 15:42 UTC, minibox24 requested changes
추천 플레이리스트에는 편집 버튼이 있으면 안됩니다

2023-08-01 11:06 UTC, kimbuckgur commented on src/components/user/Header.tsx
> +  const toggleEditMode = useCallback(() => {
킹아 ㅠㅠ

2023-08-01 11:07 UTC, kimbuckgur commented on src/pages/user/User.tsx
>            <Route path="/likes" element={<Likes />} />
리액트 포탈은 어떤가요?

2023-08-02 11:04 UTC, sandsunset commented
코드 리뷰 반영했습니다
병원 이슈로 어쩌다 보니 많이 늦어졌네요 죄송합니다 😓

2023-08-02 11:09 UTC, sandsunset commented on src/pages/user/User.tsx
>            <Route path="/likes" element={<Likes />} />
포탈도 좋지만 탭 바에 내비게이션 기능도 포함되어 있기 때문에 이 방법이 더 간결하고 직관적일거 같다고 생각합니다

2023-08-02 11:46 UTC, minibox24 approved these changes

2023-08-04 08:54 UTC, kimbuckgur commented on src/pages/user/User.tsx
>            <Route path="/likes" element={<Likes />} />
알겠습니다!

2023-08-05 05:14 UTC, merged