✨ 유튜브 플레이어 구현
wakmusic/wakmusic-pc pull request #72
Opened 2023-08-01 00:23 UTC by minibox24

# 1일 여행 가기 전 일단 올려둔 Draft PR입니다!!!!!!!!!

지금은 돌아가는 코드 정도에 불과한지라 현재 코드와 아래 작성해둔 진행 예정란 참고하시면서 어떤 부분 더 개선하면 좋을 지 코멘트 남겨주시면 감사하겠습니다

## 개요

유튜브 플레이어 구현

## 진행 에정

- 널부러진 코드 정리
- 변수명, state명들 정리
- position 바꿀 시 두번 재생 됨
- 볼륨을 로컬스토리지에 저장
- 가사 스크롤 관련 수정

## 작업 내용
- 후추

2023-08-03 18:01 UTC, unsignd commented on src/components/youtube/Youtube.tsx
> +    if (!nowPlaying) return;
다른 부분에서 하신 것처럼 or 연산자를 사용해 한줄로 처리하는 것으로 통일하면 좋을 것 같아요

2023-08-04 13:35 UTC, minibox24 commented
> ![image](https://user-images.githubusercontent.com/61652299/258433463-6784bc08-bbc8-4405-a28a-729a6825fd3e.png)
> 
> ![image](https://user-images.githubusercontent.com/61652299/258433334-4068ba2c-8fa4-422a-8037-433083d833d6.png)
> 
> 처음에 재생중인 음악이 없는 상태에서 재생 버튼을 눌러 이전에 재생했던 음악을 재생하면 위의 오류가 발생하는거 같습니다

getDuration 오류는 유튜브 iframe 자체에서 끊임없이 나오는 오류인데 대체 왜 나오는지도 모르겠고 유튜브 자체 코드에 있는 부분이라서 해결도 불가능 한 것으로 보입니다..

2023-08-04 13:36 UTC, sandsunset requested changes
https://github.com/wakmusic/wakmusic-pc/assets/61652299/dc523b15-774f-4782-9ab4-389056426edf

실제 재생중인 음악과 플레이어에서 나타내는 값이 다릅니다

2023-08-04 13:50 UTC, sandsunset requested changes
https://github.com/wakmusic/wakmusic-pc/assets/61652299/beb41c65-c654-40ce-b9f2-819aae8affb6

노래를 뒤로 재생하면 두번 들리는거 같습니다

2023-08-04 14:17 UTC, sandsunset requested changes

2023-08-04 14:17 UTC, sandsunset commented on src/components/player/Controller.tsx
> +  }
이부분은 생략해도 될거 같습니다

2023-08-04 14:21 UTC, sandsunset commented
https://github.com/wakmusic/wakmusic-pc/assets/61652299/c074f7e4-b5aa-497d-8b2d-e4ffb9dc42af

같은 노래를 재생중일때는 똑같은 노래를 누르면 다시 처음부터 재생하거나 옆에 재생목록에 쌓이지 않도록 하면 좋을거 같은데 어떻게 생각하시나요

2023-08-05 11:43 UTC, sandsunset commented
https://github.com/wakmusic/wakmusic-pc/assets/61652299/692d05ca-ce6e-4fb2-985e-91f7f80fa848

다른 노래를 재생중이어도 한번 재생했던 노래면 옆에 플레이리스트에 쌓이지 않는거 같습니다

2023-08-06 17:33 UTC, choshinyoung requested changes
다른 노래로 넘어가면 볼륨이 리셋되는것같습니다
(보이는 볼륨과 실제 볼륨이 일치하지 않습니다)

2023-08-06 17:33 UTC, choshinyoung commented on src/electron/discord.ts
> +    largeImageKey: `https://i.ytimg.com/vi/${current.songId}/default.jpg`,
여기서는 staticUtill 사용 안 하시나요?

2023-08-06 17:35 UTC, minibox24 commented on src/electron/discord.ts
> +    largeImageKey: `https://i.ytimg.com/vi/${current.songId}/default.jpg`,
앗실수

2023-08-06 18:11 UTC, minibox24 commented on src/electron/discord.ts
> +    largeImageKey: `https://i.ytimg.com/vi/${current.songId}/default.jpg`,
일렉트론이 실행되는 메인 프로세스의 타입스크립트 환경에서는 vite env를 불러올 수 없는데 굳이 개조를 하여서 모든 환경에서 필요하지도 않은 env를 불러올 바에 그냥 이렇게 쓰는게 나을 것 같아서 롤백했습니다

2023-08-07 11:15 UTC, choshinyoung approved these changes

2023-08-07 17:27 UTC, unsignd approved these changes

2023-08-07 18:05 UTC, merged