✨ 스플래시 화면
wakmusic/wakmusic-pc pull request #74
Opened 2023-08-04 09:24 UTC by minibox24

## 개요

스플래시 화면 제작

## 작업 내용

- 스플래시 화면 제작

## 스크린샷

https://github.com/wakmusic/wakmusic-pc/assets/61264156/2eefb24d-101a-4168-83af-05ec9642f337

2023-08-04 13:21 UTC, sandsunset requested changes

2023-08-04 13:21 UTC, sandsunset commented on src/components/index/Splash.tsx
> +  z-index: 999999;
z-index 값이 가장 높은 플레이어 영상 섬네일이 100으로 설정된거 같은데 999999처럼 막연하게 큰 숫자보다는 여기를 101로 설정하시거나 플레이어 부분을 함께 수정해서 적용해주시면 좋을거 같습니다

2023-08-04 13:24 UTC, sandsunset approved these changes

2023-08-05 10:16 UTC, choshinyoung approved these changes

2023-08-05 10:19 UTC, merged