✨ 아티스트 페이지 작업
wakmusic/wakmusic-pc pull request #84
Opened 2023-08-07 18:44 UTC by minibox24

## 개요

아티스트 페이지 작업

## 이슈

#82

## 작업 내용

- 아티스트 페이지의 API 작업
- 아티스트 상세 페이지 완성

2023-08-08 17:30 UTC, unsignd requested changes

2023-08-08 17:30 UTC, unsignd commented on src/apis/artist/index.ts
> +export type ArtistAlbumsSortType = "popular" | "new" | "old";
index.ts의 sortType을 공용으로 빼서 그걸 사용하면 좋을 것 같아요

2023-08-08 18:13 UTC, choshinyoung requested changes
- 아티스트 상세 페이지에서 이전 페이지로 이동이 되지 않습니다
- 전체재생, 랜덤재생 버튼도 만드셔야할것같스빈다
- 아티스트 목록의 첫줄에 호버하면 프로필 이미지 위쪽이 잘립니다
    ![image](https://github.com/wakmusic/wakmusic-pc/assets/50575654/498bc5d8-e04f-4276-bc52-50e6475d8d13)

2023-08-09 12:47 UTC, minibox24 commented on src/apis/artist/index.ts
> +export type ArtistAlbumsSortType = "popular" | "new" | "old";
#87 에서 해결

2023-08-09 13:54 UTC, unsignd approved these changes

2023-08-09 15:40 UTC, choshinyoung approved these changes

2023-08-10 08:42 UTC, merged