Api/some pages2
wakmusic/wakmusic-pc pull request #87
Opened 2023-08-08 05:19 UTC by minibox24

## 개요

몇몇 페이지 api 작업

(#80 에서 일부 코드 돚거함)

## 이슈

#85

## 작업 내용

- 메인 페이지의 왁뮤차트 API 연결
- 추천 플레이리스트 API 연결
- 왁뮤차트 API 연결
- 검색 페이지 API 연결

![image](https://github.com/wakmusic/wakmusic-pc/assets/61264156/aeeb3a78-d590-4a30-83bd-2f8879b5bd05)

2023-08-08 17:34 UTC, unsignd requested changes
화이팅!!!

2023-08-08 17:34 UTC, unsignd commented on src/apis/artist/index.ts
> +export type ArtistAlbumsSortType = "popular" | "new" | "old";
마찬가지로 index.ts의 sortType과 통일해서 하나만 쓰면 좋을 것 같습니다!

2023-08-08 17:34 UTC, unsignd commented on src/apis/songs/index.ts
> +type SearchSortType = "popular" | "new" | "old";
sortType과 위 리뷰 커맨트와 통일해서 사용해주세요

2023-08-09 13:53 UTC, unsignd approved these changes

2023-08-09 17:24 UTC, choshinyoung approved these changes

2023-08-10 08:48 UTC, merged