💫 추천 아이템 애니메이션 구현
wakmusic/wakmusic-pc pull request #98
Opened 2023-08-12 12:12 UTC by unsignd

## 개요

추천 아이템들을 8개씩 분리하고 탭 간 애니메이션을 구현하였습니다.

## 작업 내용

- 추천 아이템 8개씩 분리
- 탭 간 움직임 구현

2023-08-12 13:38 UTC, minibox24 approved these changes

2023-08-12 14:03 UTC, kimbuckgur requested changes
수정 오네가이시마수

2023-08-12 14:03 UTC, kimbuckgur commented on src/pages/index/Index.tsx
> +                ))}
reduce 부분만 따로 빼서 변수로 정의한 후 그 변수를 map 돌리는게 더 예쁠 듯 하네요

2023-08-12 14:03 UTC, kimbuckgur commented on src/pages/index/Index.tsx
> +              }}
함수로 따로 빼는 것을 추천드리옵니다

2023-08-13 00:35 UTC, minibox24 requested changes

2023-08-13 00:35 UTC, minibox24 commented on src/pages/index/Index.tsx
> +  }
utils로 분리해주세요

2023-08-13 09:26 UTC, minibox24 requested changes

2023-08-13 09:26 UTC, minibox24 commented on src/utils/listChunk.ts
> +};
다른 곳에도 재사용을 할 수 있게 타입을 제한시키지 말아주세요

2023-08-13 10:48 UTC, choshinyoung approved these changes

2023-08-13 22:49 UTC, minibox24 reviewed
혹시 any 말고 T 사용은 어떠십니까

2023-08-13 22:49 UTC, minibox24 approved these changes

2023-08-13 22:54 UTC, merged